### PR TITLE
pull changes from remote

### PR DESCRIPTION
**Pull request by pew**
Use `git pull` to pull actual files from the remote instead of using `fetch` for only the metadata

### CODE REVIEW

**Comment by whwright** [comment]
Isn't `pull` just a `fetch && merge`?

This shouldn't pull any new data, but rather just merge it into local refs from remote refs. I think this should have stayed `fetch`.

What metadata are you expecting and not getting with `fetch`?

**Comment by josegonzalez** [comment]
@whwright feel free to make a new pr to revert this.

**Comment by pew** [comment]
> Isn't `pull` just a `fetch && merge`?
> 
> This shouldn't pull any new data, but rather just merge it into local refs from remote refs. I think this should have stayed `fetch`.
> 
> What metadata are you expecting and not getting with `fetch`?

For a backup the data should also be downloaded to disk, shouldn’t it? Not just the metadata.

**Comment by whwright** [comment]
`git fetch` does download everything to disk. Changing this to `pull` just adds a `merge` into the current branch.

**Pull request merged**
