### PR TITLE
Support Python 3

### LINKED ISSUE #47: Support Python 3

### PR DESCRIPTION
**Pull request by albertyw**
Fixes #47

### CODE REVIEW

**Comment by josegonzalez** [comment]
Does this also work on Python 2.7?

**Comment by albertyw** [comment]
I updated the commits after testing manually.  It should work with python 2.7 and 3.5.  

It would be nice to have automated tests to validate though.  I tried to refactor a bit to make the code more easily testable but got caught up with setup.py and import weirdness.

**Comment by josegonzalez** [comment]
Want to take a stab at that? I can enable travis-ci if that helps.

**Comment by albertyw** [comment]
I don't have time to write tests for this by I created #49 for it.

**Pull request merged**
