### PR TITLE
#50 - refactor for friendlier import

### PR DESCRIPTION
**Pull request by timm3**
Addresses #50
--

Refactors implementation by moving it out of the `bin` script and into its own file, then having the `bin` script import what it needs.

Exposed functions in `__init__.py` so the library is easier to use when imported.

Updated `setup.py` to get `__version__` from `__init__.py` using regular expression matching, as that file now has more than just the version information.

### CODE REVIEW

**Comment by timm3** [comment]
I wasn't sure if I should open a PR from my fork's `master` branch or the feature branch. Let me know if I need to re-open it or make changes first :)

**Comment by whwright** [comment]
Was this done with `git mv`? Seems like the diff of `github-backup` should only be 4 lines. Is that a bad assumption?

**Comment by timm3** [comment]
No, I did not use `git mv`. I made a new file, copied the contents over, modified both files due to the change of file locations, and added the new file.

**Comment by josegonzalez** [comment]
Can you remove those init magic imports? Personal preference of mine to not have that sort of thing there. Only thing in that file should be the version.

**Comment by timm3** [comment]
the imports and defining of __all__ is how I got the library to be a friendlier import. I tried not using them, and none of the functions (main, etc) were able to be imported.

**Comment by timm3** [comment]
That said, I'll see if there's a better spot for it, or a different way of exposing the functions. I'm open to suggestions!

**Comment by josegonzalez** [comment]
You can import them from the submodule directly?

**Comment by timm3** [comment]
so if one wants to use this library, they'd always do `from github_backup import github_backup` instead of just `import github_backup`, and `from github_backup.github_backup import main` instead of `from github_backup import main`?

**Comment by josegonzalez** [comment]
Yes, that is correct. I'm also not going to take the PR in any other form, that one is just non-negotiable for me.

**Comment by timm3** [comment]
Alright, I'll roll with it.

Changes incoming!

**Comment by timm3** [comment]
Out of curiosity, why do you oppose the import + __all__ definition to move the functions up a level?

**Comment by timm3** [comment]
@josegonzalez alright, it should be good now.

I've tested building it, and the goals are achieved as far as I can tell.
`python setup.py sdist`
`pip install ~/path/to/built/github-backup-0.25.0.tar.gz`
github-backup is callable from commandline, and functionality is exposed when imported!

**Comment by timm3** [comment]
Should I also remove the changes I had made to `setup.py` for getting the version string, now that that's all the `__init__.py` file contains?

**Comment by timm3** [comment]
@josegonzalez anything else needed to get this accepted?

**Comment by timm3** [comment]
Closing PR because it's against Master branch and @josegonzalez is not responding.

**Comment by josegonzalez** [comment]
Oh I totally forgot to do anything with this. Mind reopening?

**Comment by josegonzalez** [comment]
I'd also remove the setup.py changes. The release script I have modifies the `__init__.py` to contain the version, which is then pulled in the `setup.py`. I can merge it after that.

**Pull request closed without merging**
