### PR TITLE
Add ability to back up gists

### PR DESCRIPTION
**Pull request by whwright**
Add ability to back up gists

This changes how things work a little bit, since you can't make the same assumptions about a gist repository as you can a regular repository. Let me know if you are open to this change.

This is working for me locally and is backwards compatible.

### CODE REVIEW

**Comment by whwright** [comment]
Do you think you will get this into a release soon, or are you wanting to do more with the code on your end?

**Comment by josegonzalez** [comment]
Damn, I just forgot to make a release. Give me a minute.

**Comment by josegonzalez** [comment]
Released in 0.17.0.

**Comment by whwright** [comment]
Thank you!

**Pull request merged**
