### PR TITLE
Revert to fetch

### PR DESCRIPTION
**Pull request by whwright**

### CODE REVIEW

**Comment by dallmair** [comment]
Reasoning (I guess) is that `fetch` works with bare repos, but `pull` doesn't.

**Comment by whwright** [comment]
That is one reason, however I also believe that `fetch` is the correct operation for a backup tool. `pull` adds a merge operation, which can change the state of your local repo if you have made any changes. I think fetching all remote refs and leaving local refs is the correct implementation.

If you never do anything with your local repo besides use this tool, there should be no difference to you.

**Comment by ColinFinck** [comment]
PR #178 indeed broke the popular option `--bare`. @josegonzalez Please merge this PR to fix that.

**Comment by josegonzalez** [comment]
Released in 0.40.1.

**Pull request merged**
