### PR TITLE
Changed to /users/{1}/repos for selectable user

### PR DESCRIPTION
**Pull request by ethus3h**
I have not tested this, but maybe it would be correct.

This is an attempt at fixing https://github.com/josegonzalez/python-github-backup/issues/94.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Mind testing it before I merge?

**Comment by ethus3h** [comment]
Ok, tested it. It works for me. Sorry, I probably should have looked into how hard it would be to test the patch instead of assuming it would be really difficult... :P

```
kyan@elegiac ~/2018oct07 nohup compiz --replace openbox $ github-backup -u ethus3h -t [redacted] --repositories --gists --wikis --issues compiz-reloaded
Backing up user compiz-reloaded to /home/kyan/2018oct07
Retrieving repositories
Requesting https://api.github.com/users/compiz-reloaded/repos?per_page=100&page=1
Requesting https://api.github.com/users/compiz-reloaded/gists?per_page=100&page=1
Filtering repositories
Backing up repositories
Updating ccsm in /home/kyan/2018oct07/repositories/ccsm/repository
Retrieving compiz-reloaded/ccsm issues
Requesting https://api.github.com/repos/compiz-reloaded/ccsm/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/ccsm/issues?filter=all&per_page=100&state=closed&page=1
Saving 14 issues to disk
Updating compicc in /home/kyan/2018oct07/repositories/compicc/repository
Retrieving compiz-reloaded/compicc issues
Requesting https://api.github.com/repos/compiz-reloaded/compicc/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compicc/issues?filter=all&per_page=100&state=closed&page=1
Saving 0 issues to disk
Cloning compiz repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz.git to /home/kyan/2018oct07/repositories/compiz/repository
Retrieving compiz-reloaded/compiz issues
Requesting https://api.github.com/repos/compiz-reloaded/compiz/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compiz/issues?filter=all&per_page=100&state=closed&page=1
Saving 16 issues to disk
Cloning compiz-bcop repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-bcop.git to /home/kyan/2018oct07/repositories/compiz-bcop/repository
Retrieving compiz-reloaded/compiz-bcop issues
Requesting https://api.github.com/repos/compiz-reloaded/compiz-bcop/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compiz-bcop/issues?filter=all&per_page=100&state=closed&page=1
Saving 0 issues to disk
Cloning compiz-boxmenu repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-boxmenu.git to /home/kyan/2018oct07/repositories/compiz-boxmenu/repository
Retrieving compiz-reloaded/compiz-boxmenu issues
Requesting https://api.github.com/repos/compiz-reloaded/compiz-boxmenu/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compiz-boxmenu/issues?filter=all&per_page=100&state=closed&page=1
Saving 1 issues to disk
Cloning compiz-debug-utils repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-debug-utils.git to /home/kyan/2018oct07/repositories/compiz-debug-utils/repository
Retrieving compiz-reloaded/compiz-debug-utils issues
Requesting https://api.github.com/repos/compiz-reloaded/compiz-debug-utils/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compiz-debug-utils/issues?filter=all&per_page=100&state=closed&page=1
Saving 0 issues to disk
Cloning compiz-manager repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-manager.git to /home/kyan/2018oct07/repositories/compiz-manager/repository
Retrieving compiz-reloaded/compiz-manager issues
Requesting https://api.github.com/repos/compiz-reloaded/compiz-manager/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compiz-manager/issues?filter=all&per_page=100&state=closed&page=1
Saving 3 issues to disk
Cloning compiz-plugins-experimental repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-plugins-experimental.git to /home/kyan/2018oct07/repositories/compiz-plugins-experimental/repository
Retrieving compiz-reloaded/compiz-plugins-experimental issues
Requesting https://api.github.com/repos/compiz-reloaded/compiz-plugins-experimental/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compiz-plugins-experimental/issues?filter=all&per_page=100&state=closed&page=1
Saving 36 issues to disk
Cloning compiz-plugins-extra repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-plugins-extra.git to /home/kyan/2018oct07/repositories/compiz-plugins-extra/repository
Retrieving compiz-reloaded/compiz-plugins-extra issues
Requesting https://api.github.com/repos/compiz-reloaded/compiz-plugins-extra/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compiz-plugins-extra/issues?filter=all&per_page=100&state=closed&page=1
Saving 15 issues to disk
Cloning compiz-plugins-main repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-plugins-main.git to /home/kyan/2018oct07/repositories/compiz-plugins-main/repository
Retrieving compiz-reloaded/compiz-plugins-main issues
Requesting https://api.github.com/repos/compiz-reloaded/compiz-plugins-main/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compiz-plugins-main/issues?filter=all&per_page=100&state=closed&page=1
Saving 26 issues to disk
^[[6~Cloning compizconfig-python repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/compizconfig-python.git to /home/kyan/2018oct07/repositories/compizconfig-python/repository
Retrieving compiz-reloaded/compizconfig-python issues
Requesting https://api.github.com/repos/compiz-reloaded/compizconfig-python/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/compizconfig-python/issues?filter=all&per_page=100&state=closed&page=1
Saving 0 issues to disk
Cloning emerald repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/emerald.git to /home/kyan/2018oct07/repositories/emerald/repository
Retrieving compiz-reloaded/emerald issues
Requesting https://api.github.com/repos/compiz-reloaded/emerald/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/emerald/issues?filter=all&per_page=100&state=closed&page=1
Saving 12 issues to disk
Cloning emerald-themes repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/emerald-themes.git to /home/kyan/2018oct07/repositories/emerald-themes/repository
Retrieving compiz-reloaded/emerald-themes issues
Requesting https://api.github.com/repos/compiz-reloaded/emerald-themes/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/emerald-themes/issues?filter=all&per_page=100&state=closed&page=1
Saving 7 issues to disk
Cloning fusion-icon repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/fusion-icon.git to /home/kyan/2018oct07/repositories/fusion-icon/repository
Retrieving compiz-reloaded/fusion-icon issues
Requesting https://api.github.com/repos/compiz-reloaded/fusion-icon/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/fusion-icon/issues?filter=all&per_page=100&state=closed&page=1
Saving 3 issues to disk
Cloning libcompizconfig repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/libcompizconfig.git to /home/kyan/2018oct07/repositories/libcompizconfig/repository
Retrieving compiz-reloaded/libcompizconfig issues
Requesting https://api.github.com/repos/compiz-reloaded/libcompizconfig/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/libcompizconfig/issues?filter=all&per_page=100&state=closed&page=1
Saving 0 issues to disk
Cloning simple-ccsm repository from https://*****:x-oauth-basic@github.com/compiz-reloaded/simple-ccsm.git to /home/kyan/2018oct07/repositories/simple-ccsm/repository
Retrieving compiz-reloaded/simple-ccsm issues
Requesting https://api.github.com/repos/compiz-reloaded/simple-ccsm/issues?filter=all&per_page=100&state=open&page=1
Requesting https://api.github.com/repos/compiz-reloaded/simple-ccsm/issues?filter=all&per_page=100&state=closed&page=1
Saving 5 issues to disk
kyan@elegiac ~/2018oct07 nohup compiz --replace openbox $ 
```

**Comment by whwright** [comment]
The git blame from that commit says the change was made for private
repos. Does this still work with private repos?

On Sun, Oct 7, 2018, at 2:54 PM, Elliot Chandler wrote:
> Ok, tested it. It works for me. Sorry, I probably should have looked
> into how hard it would be to test the patch instead of assuming it
> would be really difficult... :P


> kyan@elegiac ~/2018oct07 nohup compiz --replace openbox $ github-
> backup -u ethus3h -t [redacted] --repositories --gists --wikis --
> issues compiz-reloaded Backing up user compiz-reloaded to
> /home/kyan/2018oct07 Retrieving repositories Requesting
> https://api.github.com/users/compiz-reloaded/repos?per_page=100&page=1
> Requesting
> https://api.github.com/users/compiz-reloaded/gists?per_page=100&page=1
> Filtering repositories Backing up repositories Updating ccsm in
> /home/kyan/2018oct07/repositories/ccsm/repository Retrieving compiz-
> reloaded/ccsm issues Requesting
> https://api.github.com/repos/compiz-reloaded/ccsm/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/ccsm/issues?filter=all&per_page=100&state=closed&page=1
> Saving 14 issues to disk Updating compicc in
> /home/kyan/2018oct07/repositories/compicc/repository Retrieving compiz-
> reloaded/compicc issues Requesting
> https://api.github.com/repos/compiz-reloaded/compicc/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compicc/issues?filter=all&per_page=100&state=closed&page=1
> Saving 0 issues to disk Cloning compiz repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz.git to
> /home/kyan/2018oct07/repositories/compiz/repository Retrieving compiz-
> reloaded/compiz issues Requesting
> https://api.github.com/repos/compiz-reloaded/compiz/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compiz/issues?filter=all&per_page=100&state=closed&page=1
> Saving 16 issues to disk Cloning compiz-bcop repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-bcop.git
> to /home/kyan/2018oct07/repositories/compiz-bcop/repository Retrieving
> compiz-reloaded/compiz-bcop issues Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-bcop/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-bcop/issues?filter=all&per_page=100&state=closed&page=1
> Saving 0 issues to disk Cloning compiz-boxmenu repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-boxmenu.git
> to /home/kyan/2018oct07/repositories/compiz-boxmenu/repository
> Retrieving compiz-reloaded/compiz-boxmenu issues Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-boxmenu/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-boxmenu/issues?filter=all&per_page=100&state=closed&page=1
> Saving 1 issues to disk Cloning compiz-debug-utils repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-debug-utils.git
> to /home/kyan/2018oct07/repositories/compiz-debug-utils/repository
> Retrieving compiz-reloaded/compiz-debug-utils issues Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-debug-utils/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-debug-utils/issues?filter=all&per_page=100&state=closed&page=1
> Saving 0 issues to disk Cloning compiz-manager repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-manager.git
> to /home/kyan/2018oct07/repositories/compiz-manager/repository
> Retrieving compiz-reloaded/compiz-manager issues Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-manager/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-manager/issues?filter=all&per_page=100&state=closed&page=1
> Saving 3 issues to disk Cloning compiz-plugins-experimental repository
> from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-plugins-experimental.git
> to /home/kyan/2018oct07/repositories/compiz-plugins-
> experimental/repository Retrieving compiz-reloaded/compiz-plugins-
> experimental issues Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-plugins-experimental/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-plugins-experimental/issues?filter=all&per_page=100&state=closed&page=1
> Saving 36 issues to disk Cloning compiz-plugins-extra repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-plugins-extra.git
> to /home/kyan/2018oct07/repositories/compiz-plugins-extra/repository
> Retrieving compiz-reloaded/compiz-plugins-extra issues Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-plugins-extra/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-plugins-extra/issues?filter=all&per_page=100&state=closed&page=1
> Saving 15 issues to disk Cloning compiz-plugins-main repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/compiz-plugins-main.git
> to /home/kyan/2018oct07/repositories/compiz-plugins-main/repository
> Retrieving compiz-reloaded/compiz-plugins-main issues Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-plugins-main/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compiz-plugins-main/issues?filter=all&per_page=100&state=closed&page=1
> Saving 26 issues to disk ^[[6~Cloning compizconfig-python repository
> from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/compizconfig-python.git
> to /home/kyan/2018oct07/repositories/compizconfig-python/repository
> Retrieving compiz-reloaded/compizconfig-python issues Requesting
> https://api.github.com/repos/compiz-reloaded/compizconfig-python/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/compizconfig-python/issues?filter=all&per_page=100&state=closed&page=1
> Saving 0 issues to disk Cloning emerald repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/emerald.git to
> /home/kyan/2018oct07/repositories/emerald/repository Retrieving compiz-
> reloaded/emerald issues Requesting
> https://api.github.com/repos/compiz-reloaded/emerald/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/emerald/issues?filter=all&per_page=100&state=closed&page=1
> Saving 12 issues to disk Cloning emerald-themes repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/emerald-themes.git
> to /home/kyan/2018oct07/repositories/emerald-themes/repository
> Retrieving compiz-reloaded/emerald-themes issues Requesting
> https://api.github.com/repos/compiz-reloaded/emerald-themes/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/emerald-themes/issues?filter=all&per_page=100&state=closed&page=1
> Saving 7 issues to disk Cloning fusion-icon repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/fusion-icon.git
> to /home/kyan/2018oct07/repositories/fusion-icon/repository Retrieving
> compiz-reloaded/fusion-icon issues Requesting
> https://api.github.com/repos/compiz-reloaded/fusion-icon/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/fusion-icon/issues?filter=all&per_page=100&state=closed&page=1
> Saving 3 issues to disk Cloning libcompizconfig repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/libcompizconfig.git
> to /home/kyan/2018oct07/repositories/libcompizconfig/repository
> Retrieving compiz-reloaded/libcompizconfig issues Requesting
> https://api.github.com/repos/compiz-reloaded/libcompizconfig/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/libcompizconfig/issues?filter=all&per_page=100&state=closed&page=1
> Saving 0 issues to disk Cloning simple-ccsm repository from
> https://*****:x-oauth-basic@github.com/compiz-reloaded/simple-ccsm.git
> to /home/kyan/2018oct07/repositories/simple-ccsm/repository Retrieving
> compiz-reloaded/simple-ccsm issues Requesting
> https://api.github.com/repos/compiz-reloaded/simple-ccsm/issues?filter=all&per_page=100&state=open&page=1
> Requesting
> https://api.github.com/repos/compiz-reloaded/simple-ccsm/issues?filter=all&per_page=100&state=closed&page=1
> Saving 5 issues to disk kyan@elegiac ~/2018oct07 nohup compiz --
> replace openbox $
>> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
Links:

  1. https://github.com/josegonzalez/python-github-backup/pull/95#issuecomment-427681760

**Comment by ethus3h** [comment]
Ah, hm, no. Thanks for pointing that out @whwright. Afraid I don't know how to fix that, sorry (I suspect it would need fairly complicated logic to successfully get all repositories one has access to that are owned by a given user, since the API doesn't seem to offer that).

```
kyan@elegiac ~/2018oct07/2 nohup compiz --replace openbox $ github-backup -u ethus3h -t [redacted] -P --repositories ethus3h -R cb-status-elegiac
Backing up user ethus3h to /home/kyan/2018oct07/2
Retrieving repositories
Requesting https://api.github.com/repos/ethus3h/cb-status-elegiac?per_page=100&page=1
API request returned HTTP 404: Not Found
/bin/bash
failed with the error on /usr/bin/error-notify line 28 in /home/kyan/2018oct07/2 at 20181007170810181032756_2d303430300a:
An error was reported on  line 8 in /home/kyan/2018oct07/2 at 20181007210810164949136U2d303430300a.
kyan@elegiac ~/2018oct07/2 nohup compiz --replace openbox $ 
```

**Pull request closed without merging**
