### PR TITLE
Requests refactor

### PR DESCRIPTION
**Pull request by acdha**
While I was adding API rate-limiting I refactored to use requests for the HTTP handling since it removes some of the manual urllib2 work

### CODE REVIEW

**Comment by josegonzalez** [comment]
I'm -1 on adding requests as a dependency, as the package works just fine without requests. If you want to redo this PR with just the api retry changes, that would be nice, but I'm not merging it as is.

**Comment by acdha** [comment]
Fair enough – I'm not a fan of the extra urllib2 code but keeping it all stdlib is a reasonable decision

**Comment by acdha** [comment]
Doing it without requests looks like this:

https://github.com/acdha/python-github-backup/tree/ratelimit-retries

**Comment by josegonzalez** [comment]
That looks decent, mind issuing a PR with it?

**Pull request closed without merging**
