### PR TITLE
Preserve Unicode characters in the output file

### PR DESCRIPTION
**Pull request by kromkrom**
Added option `--write-unicode` to preserve Unicode characters in the output JSON file. This makes dumped non-ascii issues, etc. human-readable.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Why not make this default?

**Comment by kromkrom** [comment]
Actually, I don't know if there are any pitfalls with this change, since I've never used Python 2 and thus I'm inexperienced in manual unicode handling.

**Comment by josegonzalez** [comment]
Make it default. Should be fine, and if not, someone will complain :)

**Comment by kromkrom** [comment]
Ok, let's try!

**Pull request merged**
