### PR TITLE
Clone starred repos

### PR DESCRIPTION
**Pull request by whwright**
I was looking for the ability to clone starred repos as well, and stumbled across #43. So, here is my proposed solution. Please let know if you have any issues with it.

### CODE REVIEW

**Comment by whwright** [comment]
I'm also wondering if maybe this should be done under a different command line argument, since a simple upgrade to this version could cause your backup time to be _significantly_ longer. Personally, I have a lot of starred repos and some of them have thousands of issues/PRs.

**Comment by josegonzalez** [comment]
Hmmm yeah maybe this should be behind a new flag?

**Comment by whwright** [comment]
I can do that. What do you think it should be? `--starred` seems like the obvious choice, but would need to be different to maintain backwards compatibility. I can also remove it from being included when using `--all`.

**Comment by josegonzalez** [comment]
Maybe `--all-starred`? Don't include code/issues/wiki/whatever in `--all` by default (just save the fact that it was starred).

**Comment by whwright** [comment]
Opted for `--clone-starred` as it felt more descriptive. I can change to `--all-starred` if you would prefer.

**Comment by whwright** [comment]
bump... are you still interested in this change?

**Pull request merged**
