### PR TITLE
Refactor logging and add support for quiet flag

### LINKED ISSUE #190: Add a --quiet option
It would be grate to have a --quiet option to suppress any output despite warnings/errors, e.g. when running the backups as cron job.

### PR DESCRIPTION
**Pull request by whwright**
- Replace local `log_info` and `log_warning` functions with a module `logger` and `logger.info`/`logger.warning`
- Add support for `--quiet` flag by setting the level on the logger
- Resolves #190 
- This also does a little bit of setup for #182 as a module logger would be required to set different log handlers for different log levels

### CODE REVIEW

**Comment by whwright** [comment]
Any thoughts on this change?

**Comment by josegonzalez** [comment]
Mind making this `log-level` instead, like in #199?

**Comment by whwright** [comment]
> Mind making this `log-level` instead, like in #199?

Yeah I can make that change. Thanks!

**Comment by josegonzalez** [comment]
Mind rebasing?

**Comment by whwright** [comment]
I apologize for abandoning this - thank you to everyone who got it across the finish line!

**Pull request merged**
